chore: Upgrades app to modern Typescript
react-native-community/upgrade-helper pull request #375
Opened 2024-02-05 01:33 UTC by markrickert

# Summary

This PR rewrites the entire app in modern typescript. Along with this comes a lot of package upgrades now that `react-diff-view` and `framer-motion` support typescript

This addresses the Typescript support item in #108

## Test Plan

* `yarn test` runs and passes
* I added a new `yarn typecheck` command and added it to the github workflow
* I couldn't get the docker image up and running on my local M2 machine, so `yarn test-e2e` is failing locally for me.

## Checklist

- [x] I tested this thoroughly
- [x] I added the documentation in `README.md` (if needed)

2024-02-05 08:55 UTC, pvinis commented
amazing! we've been wanting to move it to TS for a while now.

Allow me a couple of days because I'm on holidays, and I will review it on Wednesday 👍.

2024-02-05 20:20 UTC, markrickert commented
No worries. The conversion to typescript found quite a few small bugs... typos, prop type mismatches, etc... so i fixed them! I've `@ts-ignore`d the places I couldn't get the linter to pass so it might be worth visiting those places in the code.

2024-02-07 17:57 UTC, pvinis approved these changes
looks great!

2024-02-07 17:58 UTC, pvinis commented
one tiny thing, i saw that the icons are not showing until hover.
<img width="1345" alt="Screenshot 2024-02-07 at 19 57 58" src="https://github.com/react-native-community/upgrade-helper/assets/100233/85b7c6b9-bc3e-4dd5-81fa-3b905546c8b9">
<img width="368" alt="Screenshot 2024-02-07 at 19 58 04" src="https://github.com/react-native-community/upgrade-helper/assets/100233/85e10e89-08c9-4de0-be76-cc959ca31afd">
fix that, and then we are good to go!

2024-02-07 17:59 UTC, pvinis approved these changes
changing to avoid accidental merge

2024-02-07 17:59 UTC, pvinis requested changes
changing to avoid accidental merge

2024-02-08 08:39 UTC, pvinis commented on src/releases/react-native/0.72.tsx
> +import type { ReleaseT } from '../types'
is that needed? ts is smart enough to know this, right?

2024-02-08 12:30 UTC, merged

2024-02-08 16:38 UTC, markrickert commented on src/releases/react-native/0.72.tsx
> +import type { ReleaseT } from '../types'
Just a style preference. The TS compiler knows the difference. 

While week on the topic, want are your thoughts on using the linter to enforce import order?